CREATE DATABASE SISDEF_SAEP

USE SISDEF_SAEP

CREATE TABLE DEFEITO(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL
);

CREATE TABLE TIPO_EQUIPAMENTO(
	ID INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL
);

CREATE TABLE EQUIPAMENTO(
	ID INT IDENTITY PRIMARY KEY,
	TIPO_EQUIPAMENTO_ID INT FOREIGN KEY REFERENCES TIPO_EQUIPAMENTO(ID),
	HORARIO DATETIME
);

CREATE TABLE REGISTRO_DEFEITO(
	ID INT IDENTITY PRIMARY KEY,
	DATA_DEFEITO DATETIME,
	EQUIPAMENTO_ID INT FOREIGN KEY REFERENCES EQUIPAMENTO(ID),
	TIPO_DEFEITO_ID INT FOREIGN KEY REFERENCES DEFEITO(ID),
	HORA_INICIAL DATETIME,
	HORA_FINAL DATETIME
);

CREATE TABLE USUARIO(
	ID INT IDENTITY PRIMARY KEY,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	SENHA VARCHAR(100) NOT NULL
);